### ISSUE TITLE
Update CSS please

### ISSUE THREAD

**Issue by baconC** [ciena-frost/ember-frost-tabs#48]
Use the CSS below to create this:
 
![image](https://cloud.githubusercontent.com/assets/17321686/23722385/25ce5034-0413-11e7-8ecd-687008c945e8.png)

.addon-demo-component {
    display: block;
    height: 250px;
    margin: 20px;
    /* padding: 10px; */
    background: #f8f8f8;
    overflow-x: auto;
}

.frost-tab .tab.active {
    border-bottom: 2px solid #404041;
}

vendor-e0beeb5….css:1
.frost-button.tab {
    height: 35px;
    box-shadow: none;
    cursor: default;
}

vendor-e0beeb5….css:1
.frost-tabs .tab-nav {
    padding-left: 10px;
    display: flex;
    flex-direction: row;
    justify-content: flex-start;
    background-color: #fff;
    margin-bottom: 0px;
}

vendor-e0beeb5….css:1
.frost-button.tab .text {
    color: #929497;
    font-size: 14px;
    margin-bottom: 2px;
    border-right: 1px solid #E8E8E8;
    padding: 2px 20px;
}

.frost-tab {
    /* padding-bottom: 2px; */
    /* border-bottom: 5px solid transparent; */
}

.content {
    padding: 20px;
    border-top: 1px solid #e8e8ef;
}

**Comment by rox163** [comment]
See PR #50
