### ISSUE TITLE
svg4everybody undefined

### ISSUE THREAD

**Issue by mukk85** [ciena-frost/ember-frost-tabs#53]
After a fresh install I am getting the following error:

Uncaught ReferenceError: svg4everybody is not defined

ember-frost-tabs: 5.2.6
ember: 2.8.1

node 6.10.3

**Comment by mukk85** [comment]
Ran a manual bower install svg4everybody and that seems to have fixed it. Not sure why this didnt install when I first installed.

**Comment by notmessenger** [comment]
Will be looked into in #76

**Comment by juwara0** [comment]
In PR: https://github.com/ciena-frost/ember-frost-tabs/pull/79 I verified that I am no longer seeing the behavior reported above.
