### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by sibijohn72** [ciena-frost/ember-frost-tabs#57]
Hi, I just did a fresh install of ember-frost-tabs and its throwing the following error.

`Build failed.
The Broccoli Plugin: [SvgProcessor: SVGStore Processor] failed with:
Error: Path must be absolute: "C:\my-project\tmp\svg_processor-output_path-eZimw3du.tmp"
    at Object.assertAbsolutePaths (C:\my-project\node_modules\broccoli-kitchen-sink-helpers\in
dex.js:174:13)`

**Comment by sibijohn72** [comment]
Same issue here : 
https://github.com/ciena-frost/ember-frost-modal/issues/69

**Comment by notmessenger** [comment]
This will be evaluated in #76

**Comment by juwara0** [comment]
In PR: https://github.com/ciena-frost/ember-frost-tabs/pull/79 I verified that I am no longer seeing the behavior reported above.
