### ISSUE TITLE
Enhance frost-detail-tab-actions to display actions labels in popover. 

### ISSUE THREAD

**Issue by goforsatish** [ciena-frost/ember-frost-tabs#88]
Are you opening a **BUG REPORT** or a **FEATURE REQUEST / CODE CHANGE**?

There is a section for each below.  Please complete the appropriate section and remove the other one.

We realize there is a lot of data requested here. We ask only that you do your best to provide as much information as possible so we can better help you.

# FEATURE REQUEST / CODE CHANGE

* [x] I have deleted the **BUG REPORT** section

## Summary
Enhance frost-detail-tab-actions to display action label in popover. 
Currently, actions labels are displayed below the each action icon that makes action bar look cluttered in case of many actions on action bar as the icon as well as labels take space on action bar for an action. Displaying only actions icons on the action bar will provide more real estate for other icons. The tooltip will display the corresponding actin label on mouseover on each action. 

## Motivation
Enhance frost-detail-tab-actions to display action label in popover. 
Currently, actions labels are displayed below the each action icon that makes action bar look cluttered in case of many actions on action bar as the icon as well as labels take space on action bar for an action. Displaying only actions icons on the action bar will provide more real estate for other icons. The tooltip will display the corresponding actin label on mouseover on each action. 

## Detailed design
This is the bulk of the Feature Request / Code Change.

Explain the design in enough detail for somebody familiar with this addon, the UI Platform ecosystem, and Ember.js to understand, and for somebody familiar with the implementation to implement. This should get into specifics and corner-cases, and include examples of how the feature is used. Any new terminology should be defined here.

## How we teach this
frost-detail-tab-actions bar enhancement  to display action labels in tooltip

## Drawbacks
None
## Alternatives
User will be limited to use only a few actions on action bar as he needs space to display both icons and label. However, with the new design use can utilise the maximum real estate of action bar to display action icons and their labels can be seen in popover on mouse over event.

**Comment by notmessenger** [comment]
Before this is implemented we need verification from @ccampbel @sonyathornley (and crew) that this is a desired/allowable change.
